# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

adjust_S_copy <- function(S, u, current, target, n, gamma) {
    .Call('ramcmc_adjust_S_copy', PACKAGE = 'ramcmc', S, u, current, target, n, gamma)
}

cholupdate <- function(L, u) {
    .Call('ramcmc_cholupdate', PACKAGE = 'ramcmc', L, u)
}

choldowndate <- function(L, u) {
    .Call('ramcmc_choldowndate', PACKAGE = 'ramcmc', L, u)
}

adjust_S <- function(S, u, current, target, n, gamma) {
    invisible(.Call('ramcmc_adjust_S', PACKAGE = 'ramcmc', S, u, current, target, n, gamma))
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('ramcmc_RcppExport_registerCCallable', PACKAGE = 'ramcmc')
})
